### ISSUE TITLE
LUA Cache fn purpose

### ISSUE THREAD

**Issue by mhmdkanj** [taylorhakes/python-redis-cache#37]
Hey there, not sure if this is the right place to ask, but I was curious as to why does the library attach an LUA script to the Redis client (not sure what it's supposed to do).

**Comment by taylorhakes** [comment]
Hey, thanks for the question. It takes care of the `limit` and `ttl` parameters. There is a redis key that keeps track of all the keys in use. The Lua script allows the code to do all the operations in one trip to redis and avoids a round trip (Read from redis, evaluation in python and then send another redis request). It unfortunately can't be done with a redis pipeline for instance (which is atomic) because I need to get the results from a redis `GET` and do operations based on it.  Does that make sense?

If you are able to find a way to do it without Lua, please let me know.

**Comment by mhmdkanj** [comment]
Ah okay - so if I got this right, the things that are done in one trip to redis include:
- getting/setting cached values
- checking for the `limit` and revoke the appropriate keys if exceeded
- assign a ttl if it's a positive value

assuming we're not dealing with atomic ops.
